### PR TITLE
This commit bumps up the version of uMurmur to 0.2.20.

### PR DESCRIPTION
**Pull request by hw-lunemann**
An upstream patch was removed as it is obsolete now.

### CODE REVIEW

**Comment by hw-lunemann** [comment]
Tested it on my fritzbox!

Building with autotools has been deprecated a few versions ago but still works fine.

**Comment by hw-lunemann** [comment]
I just noticed that all Umlaute in the wiki docs have been removed by docs/generate.sh

What could have caused that to happen?

**Comment by fda77** [comment]
Your linux user or system has no UTF8 locale. This is checked now with 393c8f73aa08bd2c0bc1a6071e3195b385dc159b

**Comment by hw-lunemann** [comment]
Ah, I SSHed into my developement machine for this. I guess UTF8 got lost there as both my host and developement machine are UTF8?

`echo $LANG` returns `en_US.UTF-8` and `locale charmap` returns `UTF-8` for both of them, even through ssh.

**Comment by fda77** [comment]
Im not sure anymore...
When i ran `LANG=C docs/generate.sh` all umlauts where removed.

**Pull request merged**
