### PR TITLE
Add support of Fritz_Box_HW259 - FRITZ!Box 7590 AX

### PR DESCRIPTION
**Pull request by Ircama**
Add support of product "Fritz_Box_HW259", referring to FRITZ!Box 7590 AX and 7590 AX v2, including "Edition International".

Check discussion https://github.com/Freetz-NG/freetz-ng/discussions/923 for details.

Restores changes made with https://github.com/Freetz-NG/freetz-ng/commit/48ce67fb917fb904d8b55d6927247967177c1574.

### CODE REVIEW

**Comment by fda77** [comment]
> Check discussion https://github.com/Freetz-NG/freetz-ng/discussions/923 for details.

thats a good idea.. i do not want to write again what i wrote there

**Comment by Ircama** [comment]
> > Check discussion #923 for details.
> 
> thats a good idea.. i do not want to write again what i wrote there

What do you mean here?

**Comment by fda77** [comment]
I dont understand your question

**Comment by Ircama** [comment]
I newly performed all tests after better understanding the *push_firmware* process.

Commit https://github.com/Freetz-NG/freetz-ng/commit/0496bc6813c01c5d579d585d229a246246dc7255 was ok with command `tools/push_firmware` (without options) and allows to load the firmware.
 
Anyway, after the following message the user shall manually do a power cycle; it is indeed not clear for new users. One that does not know what happens, can't imagine that a power cycle is actually needed and thinks that the upload process does not work.

```
 * Detected linux_fs_start: '0'
 * Designated linux_fs_start: 1

 * No reply from box, assuming switch-off or restart. Trying to re-detect box.
   Waiting .....................................
```

Strictly subsequently, commit https://github.com/Freetz-NG/freetz-ng/commit/48ce67fb917fb904d8b55d6927247967177c1574 did not allow to load the firmware any more (see below the result).

Reverting https://github.com/Freetz-NG/freetz-ng/commit/48ce67fb917fb904d8b55d6927247967177c1574 allows successfully testing some options:

- `tools/push_firmware` works!
- `tools/push_firmware -ram 0` does not work.
- `tools/push_firmware -ram 200` works.
- `tools/push_firmware -ram 250` works.
- `tools/push_firmware -ram 512` does not work.

Again, one that does not know, considers that 7590 AX has 512 MB RAM and wrongly performs the testing with the last value.

In summary, reverting https://github.com/Freetz-NG/freetz-ng/commit/48ce67fb917fb904d8b55d6927247967177c1574 is needed.

This PR does that, then sets appropriate values for Fritz_Box_HW259 (even if the default works) and adds useful information that some device needs a reboot.

Please find below the logs.

-----------------------------

Using the latest *push_firmware* in this repo, the upload does not work:

```
$ git clone https://github.com/Freetz-NG/freetz-ng ~/freetz-ng-master
$ cp ~/freetz-ng-master/tools/push_firmware .
$ tools/push_firmware

 * Analyzing 'images/7590AX_07.70.all-rev110391_inhaus_freetz-ng-23069M-be072c1ff_20240125-052206.image' ...

 * Warning: It seems your network is not able to reach
   192.168.178.1 directly. One(!) of these commands could help to fix:
bonding_masters: error fetching interface information: Device not found
   $ sudo ifconfig bonding_masters:0 192.168.178. up
   $ sudo ifconfig eth0:0 192.168.178.240 up
   Proceed anyway? ([y]/n) y
 * Product: Fritz_Box_HW259 (FRITZ!Box 7590 AX)
 * Using command: ftp
 * Target host: 192.168.178.1
 * Outgoing IP: unknown
 * Flash mode: ram-boot
 * Allowed memory size: 208 MB
 * Designated linux_fs_start: <other>

 !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!!
 !!!  THERE IS NO WARRANTY AT ALL !!! USE AT YOUR OWN RISK   !!!

 * Are you sure, that you want to flash this file to the device?
   images/7590AX_07.70.all-rev110391_inhaus_freetz-ng-23069M-be072c1ff_20240125-052206.image
   Proceed? (y/[n]) y

 * You should now reboot your box (192.168.178.1). Waiting for shut down.
   Switch off, if reboot is not detected because it happens too quickly.
   Some newer bootloader versions allow to flash on power-cycle only.

 * MAPSTART=0x80000000
 * FULLSIZE=0x0D000000   (208 MB)
 * MAPLIMIT=0x8d000000
 * FILESIZE=0x032e2700   (~50 MB)
 * ALIBYTES=0x00000000   (~0 kB)
 * FREESIZE=0x09d1d900   (~157 MB)
 * MTDSTART=0x89d1d900

 * No reply from box, assuming switch-off or restart. Trying to re-detect box.
   Waiting .......................................................................... found!

 * Detected linux_fs_start: '0'
 * Designated linux_fs_start: 1

 * Box is back up again, initiating transfer.

ftp: connect: No route to host
Not connected.
Debugging on (debug=1).
Not connected.
Not connected.
Not connected.
Not connected.
Not connected.
Not connected.

done
```

Using the push_firmware of this PR, the upload works:

```
$ mkdir tools/p
$ cd tools/p
$ wget https://github.com/Freetz-NG/freetz-ng/pull/926.patch
$ cd ../..
$ patch -p1 < tools/p/926.patch
patching file tools/push_firmware
$ rm -rf tools/p
$ tools/push_firmware

 * Analyzing 'images/7590AX_07.70.all-rev110391_inhaus_freetz-ng-23069M-be072c1ff_20240125-052206.image' ...

 * Warning: It seems your network is not able to reach
   192.168.178.1 directly. One(!) of these commands could help to fix:
bonding_masters: error fetching interface information: Device not found
   $ sudo ifconfig bonding_masters:0 192.168.178. up
   $ sudo ifconfig eth0:0 192.168.178.240 up
   Proceed anyway? ([y]/n) y
 * Product: Fritz_Box_HW259 (FRITZ!Box 7590 AX)
 * Using command: ftp
 * Target host: 192.168.178.1
 * Outgoing IP: unknown
 * Flash mode: ram-boot
 * Allowed memory size: 192 MB
 * Designated linux_fs_start: <other>

 !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!!
 !!!  THERE IS NO WARRANTY AT ALL !!! USE AT YOUR OWN RISK   !!!

 * Are you sure, that you want to flash this file to the device?
   images/7590AX_07.70.all-rev110391_inhaus_freetz-ng-23069M-be072c1ff_20240125-052206.image
   Proceed? (y/[n]) y

 * You should now reboot your box (192.168.178.1). Waiting for shut down.
   Switch off, if reboot is not detected because it happens too quickly.
   Some newer bootloader versions allow to flash on power-cycle only.

 * MAPSTART=0x80000000
 * FULLSIZE=0x0C000000   (192 MB)
 * MAPLIMIT=0x8c000000
 * FILESIZE=0x032e2700   (~50 MB)
 * ALIBYTES=0x00000000   (~0 kB)
 * FREESIZE=0x08d1d900   (~141 MB)
 * MTDSTART=0x88d1d900

 * No reply from box, assuming switch-off or restart. Trying to re-detect box.
   Waiting .............................. found!

 * Detected linux_fs_start: '0'
 * Designated linux_fs_start: 1

 * A reboot has been issued. Please manually unplug the power socket
   and plug it again if the box does not reboot itself.

 * No reply from box, assuming switch-off or restart. Trying to re-detect box.
   Waiting ....................... found!

 * Box is back up again, initiating transfer.

Connected to 192.168.178.1.
220 ADAM2 FTP Server ready
331 Password required for adam2
230 User adam2 successfully logged in
Remote system type is AVM.
Debugging on (debug=1).
---> TYPE I
200 Type set to BINARY
---> MEDIA SDRAM
200 Media set to MEDIA_SDRAM
---> SETENV memsize 0x08d1d900
200 SETENV command successful
---> SETENV kernel_args_tmp mtdram1=0x88d1d900,0x8c000000
200 SETENV command successful
local: /tmp/freetz_KXq/ramboot.flash remote: 0x88d1d900 0x8c000000
---> PASV
227 Entering Passive Mode (192,168,178,1,12,13)
---> STOR 0x88d1d900 0x8c000000
150 Opening BINARY data connection
226 Transfer complete
53356288 bytes sent in 12.27 secs (4.1485 MB/s)
---> SETENV linux_fs_start 1
200 SETENV command successful
---> QUIT
221 Thank you for using the FTP service on ADAM2

done
$
```

Using the push_firmware obtained reverting https://github.com/Freetz-NG/freetz-ng/commit/48ce67fb917fb904d8b55d6927247967177c1574 works, but the user must understand that a plysical power cycle must be done in the middle of the procedure.

```
$ tools/push_firmware

 * Analyzing 'images/7590AX_07.70.all-rev110391_inhaus_freetz-ng-23069M-be072c1ff_20240125-052206.image' ...

 * Warning: It seems your network is not able to reach
   192.168.178.1 directly. One(!) of these commands could help to fix:
bonding_masters: error fetching interface information: Device not found
   $ sudo ifconfig bonding_masters:0 192.168.178. up
   $ sudo ifconfig eth0:0 192.168.178.240 up
   Proceed anyway? ([y]/n) y
 * Product: Fritz_Box_HW259 (FRITZ!Box 7590 AX)
 * Using command: ftp
 * Target host: 192.168.178.1
 * Outgoing IP: unknown
 * Flash mode: ram-boot
 * Allowed memory size: 208 MB
 * Designated linux_fs_start: <other>

 !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!!
 !!!  THERE IS NO WARRANTY AT ALL !!! USE AT YOUR OWN RISK   !!!

 * Are you sure, that you want to flash this file to the device?
   images/7590AX_07.70.all-rev110391_inhaus_freetz-ng-23069M-be072c1ff_20240125-052206.image
   Proceed? (y/[n]) y

 * You should now reboot your box (192.168.178.1). Waiting for shut down.
   Switch off, if reboot is not detected because it happens too quickly.
   Some newer bootloader versions allow to flash on power-cycle only.

 * MAPSTART=0x80000000
 * FULLSIZE=0x0D000000   (208 MB)
 * MAPLIMIT=0x8d000000
 * FILESIZE=0x032e2700   (~50 MB)
 * ALIBYTES=0x00000000   (~0 kB)
 * FREESIZE=0x09d1d900   (~157 MB)
 * MTDSTART=0x89d1d900

 * No reply from box, assuming switch-off or restart. Trying to re-detect box.
   Waiting .................... found!

 * Detected linux_fs_start: '1'
 * Designated linux_fs_start: 0

 * No reply from box, assuming switch-off or restart. Trying to re-detect box.
   Waiting ............
```

Here I performed a power cycle.

```
                       ........... found!

 * Box is back up again, initiating transfer.

Connected to 192.168.178.1.
220 ADAM2 FTP Server ready
331 Password required for adam2
230 User adam2 successfully logged in
Remote system type is AVM.
Debugging on (debug=1).
---> TYPE I
200 Type set to BINARY
---> MEDIA SDRAM
200 Media set to MEDIA_SDRAM
---> SETENV memsize 0x09d1d900
200 SETENV command successful
---> SETENV kernel_args_tmp mtdram1=0x89d1d900,0x8d000000
200 SETENV command successful
local: /tmp/freetz_KdY/ramboot.flash remote: 0x89d1d900 0x8d000000
---> PASV
227 Entering Passive Mode (192,168,178,1,12,11)
---> STOR 0x89d1d900 0x8d000000
150 Opening BINARY data connection
226 Transfer complete
53356288 bytes sent in 12.89 secs (3.9471 MB/s)
---> SETENV linux_fs_start 0
200 SETENV command successful
---> QUIT
221 Thank you for using the FTP service on ADAM2

done
```

------------------------------

The whole description here became a bit long, but I hope it helps to clarify everything.

At the end, I found an irrelevant bug meanwhile, that [`[ "$WAIT_FOR_LOADER_DONE" == "y" ] && return`](https://github.com/Ircama/freetz-ng/blob/7c66aabdb160cc640043178812bd58935782363d/tools/push_firmware#L51) needs to be removed. I'll update this PR in the next minute to correct this.

**Comment by fda77** [comment]
It is possible that the  208 and the maximum 512mb does not work. Thats why i asked you a long time ago to do a tcpdump/wireshark dump to get the value avm uses.
Some devices use more than 2 cpu and split the ram between. This value could also change for the same device but different fritzos version! So all new versions are "untested" and this could only be verified by a dump. 
Someone should write a tool to extract it from recovery. 
I can use a adam2-emulator for this but i then still need the booloader-environment...

Your connection problems could be caused of WSL with its routing (including nat?). As the 2 "reboot" are replaced (like avm does it) there are less problems finding the device

from help of PF:
> For ram-boot mode you may need to set a larger '-ram' value then the default of '208' MB.
> You could use '-ram 0' to detect the size and use the maximum. The value AVM uses is
> hardcoded into the recovery file and does not always use all available memory. A smaller
> value is okay as long as the image in the ram has enough ram to boot and flash itsef.

**Comment by Ircama** [comment]
> Thats why i asked you a long time ago to do a tcpdump/wireshark dump to get the value avm uses.

Your hint was crucial. I owed posts and PR in recognition of such support.

> Your connection problems could be caused of WSL with its routing (including nat?). As the 2 "reboot" are replaced (like avm does it) there are less problems finding the device

Not really, I confirm that the 7590 AX device is not compatible with the current version of push_firmware. Anyway, if I apply this patch, the firmware can be uploaded. I have now FRITZ!OS 7.80 with the latest pull of freetz-ng.

**Comment by fda77** [comment]
Only the "FULLSIZE" definition should be enough. But what is the value AVM uses? Really 192?

**Comment by Ircama** [comment]
> Really 192?

Yes, it is.

This was the log from the recovery tool:

- %localappdata%\VirtualStore\Windows\ftp.log:

```
2:24:023: 2.01 gitbuild:1038875
2:24:023: Registry: SYSTEM\CurrentControlSet\Services\TcpIp\Parameters\DisableDHCPMediaSense=0
2:24:023: recover-firmware-id:		259
2:24:023: recover-firmware-version:	259.07.57
2:24:338: check adapter(Intel(R) Ethernet Connection I219-LM) adapter 0x4: Ip: 0.0.0.0(0.0.0.0) (static)
2:24:341: get ipaddress from registry 192.168.178.220
2:24:341: compatible ipaddress (static) found: 192.168.178.220 on adapter 0x4
2:24:373: search on addr: 192.168.178.1
3:24:727: search on addr: 192.168.178.1
4:25:097: search on addr: 192.168.178.1
5:25:423: search on addr: 192.168.178.1
6:25:986: search on addr: 192.168.178.1
7:26:443: search on addr: 192.168.178.1
8:26:795: search on addr: 192.168.178.1
9:27:362: search on addr: 192.168.178.1
9:45:552: ---> read environment <---
9:45:657: open ftp 192.168.178.1 port 21
9:45:676: recv: 220 ADAM2 FTP Server ready
9:45:677: send: USER adam2
9:45:677: recv: 331 Password required for adam2
9:45:678: send: PASS adam2
9:45:678: recv: 230 User adam2 successfully logged in
9:45:679: send: SYST
9:45:679: recv: 215 AVM EVA Version 1.11744 0x0 0x46409
9:45:679: send: TYPE I
9:45:679: recv: 200 Type set to BINARY
9:45:680: send: MEDIA SDRAM
9:45:680: recv: 200 Media set to MEDIA_SDRAM
9:45:680: send: P@SW
9:45:680: recv: 227 Entering Passive Mode (192,168,178,1,12,11)
9:45:680: open ftp data 192.168.178.1 port 3083
9:45:681: send: RETR env
9:45:681: recv: 150 Opening BINARY data connection
9:45:794: recv: 226 Transfer complete
9:45:907: environment successfully read(1446 bytes)
9:45:907: send: USER adam2
9:45:907: recv: 331 Password required for adam2
9:45:908: send: PASS adam2
9:45:908: recv: 230 User adam2 successfully logged in
9:45:909: send: SYST
9:45:909: recv: 215 AVM EVA Version 1.11744 0x0 0x46409
9:45:909: send: TYPE I
9:45:909: recv: 200 Type set to BINARY
9:45:909: send: MEDIA SDRAM
9:45:909: recv: 200 Media set to MEDIA_SDRAM
9:45:910: send: P@SW
9:45:910: recv: 227 Entering Passive Mode (192,168,178,1,12,1)
9:45:910: open ftp data 192.168.178.1 port 3073
9:45:915: send: RETR count
9:45:915: recv: 150 Opening BINARY data connection
9:45:969: recv: 226 Transfer complete
9:46:098: environment successfully read(153 bytes)
9:46:105: send: BYE
9:46:105: recv: 221 Thank you for using the FTP service on ADAM2
9:46:127: 	hardware-revision:	259
9:46:127: 	firmware-version:	259.07.70
9:46:127: 	urloader-version:	1.11744
9:46:127: 	oem:	avme
9:46:127: 	provider:	
9:46:770: set defaultsettings mtdnand (size: 2104)
9:46:770: ---> write image (mtdnand) <---
9:46:879: open ftp 192.168.178.1 port 21
9:46:913: recv: 220 ADAM2 FTP Server ready
9:46:926: send: USER adam2
9:46:926: recv: 331 Password required for adam2
9:46:926: send: PASS adam2
9:46:926: recv: 230 User adam2 successfully logged in
9:46:927: send: SYST
9:46:927: recv: 215 AVM EVA Version 1.11744 0x0 0x46409
9:46:927: send: TYPE I
9:46:927: recv: 200 Type set to BINARY
9:46:927: send: MEDIA FLSH
9:46:927: recv: 200 Media set to MEDIA_FLASH
9:46:927: send: P@SW
9:46:927: recv: 227 Entering Passive Mode (192,168,178,1,12,5)
9:46:927: open ftp data 192.168.178.1 port 3077
9:46:929: clear flash-partition (mtdnand)
9:47:674: send: STOR mtdnand
9:47:674: recv: 150 Opening BINARY data connection
9:47:755: flash clear (mtdnand) ok : now send image
9:47:865: update flash-partition (mtdnand)
9:47:890: send image (size=2104) for mtd8
9:48:596: recv: 226 Transfer complete
9:48:596: flash write (mtd8) ok
9:48:720: successfully update of mtd8
9:48:720: send: BYE
9:48:720: recv: 221 Thank you for using the FTP service on ADAM2
9:50:802: nand: load filesystem and kernel image to RAM (size: 39825920)
9:50:802: ---> read environment <---
9:50:902: open ftp 192.168.178.1 port 21
9:50:927: recv: 220 ADAM2 FTP Server ready
9:50:927: send: USER adam2
9:50:927: recv: 331 Password required for adam2
9:50:928: send: PASS adam2
9:50:928: recv: 230 User adam2 successfully logged in
9:50:928: send: SYST
9:50:928: recv: 215 AVM EVA Version 1.11744 0x0 0x46409
9:50:929: send: TYPE I
9:50:929: recv: 200 Type set to BINARY
9:50:929: send: MEDIA SDRAM
9:50:929: recv: 200 Media set to MEDIA_SDRAM
9:50:930: send: P@SW
9:50:930: recv: 227 Entering Passive Mode (192,168,178,1,12,0)
9:50:930: open ftp data 192.168.178.1 port 3072
9:50:932: send: RETR env
9:50:932: recv: 150 Opening BINARY data connection
9:51:082: recv: 226 Transfer complete
9:51:189: environment successfully read(1345 bytes)
9:51:190: send: BYE
9:51:190: recv: 221 Thank you for using the FTP service on ADAM2
9:51:194: ramload: savekernel activ for NAND
9:51:199: ---> write image mtd1 mtd1-base/size(900000/800000)ram-base/size(80000000/c000000) SquashFS(offset=0x6e1200 - 31.101 MiB) <---
9:51:312: open ftp 192.168.178.1 port 21
9:51:332: recv: 220 ADAM2 FTP Server ready
9:51:343: send: USER adam2
9:51:343: recv: 331 Password required for adam2
9:51:344: send: PASS adam2
9:51:344: recv: 230 User adam2 successfully logged in
9:51:344: send: SYST
9:51:344: recv: 215 AVM EVA Version 1.11744 0x0 0x46409
9:51:348: send: SETENV memsize 0x99fee00
9:51:348: recv: 200 SETENV command successful
9:51:348: send: SETENV kernel_args_tmp mtdram1=0x899fee00,0x8c000000
9:51:348: recv: 200 SETENV command successful
9:51:349: send: TYPE I
9:51:349: recv: 200 Type set to BINARY
9:51:349: send: MEDIA SDRAM
9:51:349: recv: 200 Media set to MEDIA_SDRAM
9:51:350: send: P@SW
9:51:350: recv: 227 Entering Passive Mode (192,168,178,1,12,27)
9:51:350: open ftp data 192.168.178.1 port 3099
9:51:351: RAM-Load Image to 899fee00 Filesystem: 8a0e0000
9:51:352: send: STOR 0x899fee00 0x8c000000
9:51:352: recv: 150 Opening BINARY data connection
9:51:352: now send image mtd1 to ram
9:51:374: send image (size=39825920) for mtd1
10:08:449: recv: 226 Transfer complete
10:08:449: load to ram (mtd1) ok
10:44:131: ----EOF---
```

- %localappdata%\VirtualStore\Windows\environment.log:

```
DMC                   SL1,nonFPGA
HWRevision            259
HWSubRevision         32
ProductID             Fritz_Box_HW259
...
annex                 A
autoload              yes
bootloaderVersion     1.11744
country               039
firstfreeaddress      0x80000000
firmware_info         259.07.70
firmware_version      avme
flashsize             nor_size=0MB sflash_size=0KB nand_size=512MB
language              it
linux_fs_start        1
...
memsize               0x0c000000
mtd0                  0x0,0x2C00000
mtd1                  0x900000,0x1100000
mtd2                  0x0,0x100000
mtd3                  0x100000,0x900000
mtd4                  0x1100000,0x1900000
mtd5                  0x1900000,0x20000000
my_ipaddress          192.168.178.1
prompt                Eva_AVM
...
usb_device_id         0x0000
usb_device_name       USB DSL Device
usb_manufacturer_name  AVM
usb_revision_id       0x0000
...
wlan_ssid             FRITZ!Box#7590#QA
```

**Comment by fda77** [comment]
Thx, so lets use `0x0c000000` like in the PR
Btw, some one should write a recovery-analyze tool to get these values...

The "missing" ram could be assigned another core. My 7490 shows with "free" command only 233,5mb total ram (of 256). Or a 6490 shows 226mb of 512

**Comment by fda77** [comment]
@Ircama Can you post your environment? You could get it with "cat /proc/sys/urlader/environment" or by bootloader. I have only a broken one and avm recovery shows
```
FRITZ!Box 7590 AX suchen
Eine Anlage gefunden! - Ermitteln der aktuellen Version.
Version erfolgreich ermittelt!
    Hardware:	FRITZ!Box 7590 AX
    Urlader:	11275
    Firmware:	
Firmware der FRITZ!Box 7590 AX ist mit der Recover-Firmware inkompatibel
```
it could be anonymized like
```
DMC:  SL1
HWRevision:  259
HWSubRevision:  2
ProductID:  Fritz_Box_HW259
SerialNumber:  X12345678901234
annex:  B
autoload:  yes
bootloaderVersion:  1.11275
country:  049
firstfreeaddress:  0x852A6A00
firmware_info:  259.07.28
firmware_version:  avm
flashsize:  nor_size=0MB sflash_size=0KB nand_size=512MB
language:  de
linux_fs_start:  1
maca:  3C:37:12:*
macb:  3C:37:12:*
macwlan:  3C:37:12:*
macwlan2:  3C:37:12:*
macdsl:  3C:37:12:*
memsize:  0x20000000
mtd0:  0x0,0x2C00000
mtd1:  0x900000,0x1100000
mtd2:  0x0,0x100000
mtd3:  0x100000,0x900000
mtd4:  0x1100000,0x1900000
mtd5:  0x1900000,0x20000000
my_ipaddress:  192.168.178.1
prompt:  Eva_AVM
tr069_passphrase:  123456789012
tr069_serial:  00040E-3C3712*
usb_board_mac:  3C:37:12:*
usb_device_id:  0x0000
usb_device_name:  USB DSL Device
usb_manufacturer_name:  AVM
usb_revision_id:  0x0000
usb_rndis_mac:  3C:37:12:*
webgui_pass:  12345678
wlan_key:  1234567890123456
wlan_ssid:  FRITZ!Box#7590#XX
```

**Comment by Ircama** [comment]
```
cat /proc/sys/urlader/environment
```

```
DMC     SL1,nonFPGA
HWRevision      259
HWSubRevision   32
ProductID       Fritz_Box_HW259
SerialNumber    R...
annex   A
autoload        yes
bootloaderVersion       1.11744
country 039
firstfreeaddress        0x852A7500
firmware_info   259.07.80
firmware_version        avme
flashsize       nor_size=0MB sflash_size=0KB nand_size=512MB
language        it
linux_fs_start  1
maca    0C:72:74:...
macb    0C:72:74:...
macwlan 0C:72:74:...
macwlan2        0C:72:74:...
macdsl  0C:72:74:...
memsize 0x20000000
mtd0    0x0,0x2C00000
mtd1    0x900000,0x1100000
mtd2    0x0,0x100000
mtd3    0x100000,0x900000
mtd4    0x1100000,0x1900000
mtd5    0x1900000,0x20000000
my_ipaddress    192.168.178.1
prompt  Eva_AVM
ptest
tr069_passphrase        ...
tr069_serial    00040E-...
usb_board_mac   0C:72:74:...
usb_device_id   0x0000
usb_device_name USB DSL Device
usb_manufacturer_name   AVM
usb_revision_id 0x0000
usb_rndis_mac   0C:72:74:...
webgui_pass     ...
wlan_key        ...
wlan_ssid       FRITZ!Box#7590#QA
```

**Comment by Ircama** [comment]
>  I have only a broken one

When I ran the recovery tool, it downloaded the env and count files and then stored mtdnand (this one generated by the recovery tool). Interactively, I can download env and count, but not mtdnand.

**Comment by fda77** [comment]
Thx!
Avm reeds the env and then builds a empty config partition which is then written. But pushfirmware does notheing with the config-partitoin. Someone wrote in IPPF how to do it by yourself (docsis devices dont have a recovery)

**Comment by fda77** [comment]
There is notghing new in your env, im wondering why mine does not work with the eva emulator.
Maybe the recovery does not like the bootloaderVersion?
Or the missing "nonFPGA" in `DMC:  SL1,nonFPGA`  ?

**Comment by Ircama** [comment]
> There is notghing new in your env, im wondering why mine does not work with the eva emulator.

Please check whether https://github.com/Freetz-NG/freetz-ng/commit/04239148a3a3b5956a7adc59b5431b9c316bd362#commitcomment-138252964 could help.

Adding here `get env` (from the FTP at boot):

```
DMC                   SL1,nonFPGA
HWRevision            259
HWSubRevision         32
ProductID             Fritz_Box_HW259
SerialNumber          R...
annex                 A
autoload              yes
bootloaderVersion     1.11744
country               039
firstfreeaddress      0x80000000
firmware_info         259.07.80
firmware_version      avme
flashsize             nor_size=0MB sflash_size=0KB nand_size=512MB
language              it
linux_fs_start        1
maca                  0C:72:74:...
macb                  0C:72:74:...
macwlan               0C:72:74:...
macwlan2              0C:72:74:...
macdsl                0C:72:74:...
memsize               0x0c000000
mtd0                  0x0,0x2C00000
mtd1                  0x900000,0x1100000
mtd2                  0x0,0x100000
mtd3                  0x100000,0x900000
mtd4                  0x1100000,0x1900000
mtd5                  0x1900000,0x20000000
my_ipaddress          192.168.178.1
prompt                Eva_AVM
ptest
tr069_passphrase      ...
tr069_serial          ...
usb_board_mac         0C:72:74:...
usb_device_id         0x0000
usb_device_name       USB DSL Device
usb_manufacturer_name  AVM
usb_revision_id       0x0000
usb_rndis_mac         0C:72:74:...
webgui_pass           ...
wlan_key              ...
wlan_ssid             FRITZ!Box#7590#QA
```

Notice the different `firstfreeaddress` and `memsize` (the other values are the same). The right values for loading the firmware appear to be the ones of `get env`. Notice also that `quote GETENV` from the FTP at boot gets the wrong values.

**Comment by Ircama** [comment]
> Someone should write a tool to extract it from recovery.

Check whether this code https://github.com/Freetz-NG/freetz-ng/compare/master...Ircama:freetz-ng:ircama_avm_recovery_tool_log_analyzer fits (including commit description). It should be tested with different logs before producing a PR. It analyses *%localappdata%\VirtualStore\Windows\environment.log*.

Anyway, I would be more oriented to simply reading *firstfreeaddress* and *memsize* from `notepad %localappdata%\VirtualStore\Windows\environment.log`.

**Comment by fda77** [comment]
I can not read python like bash. Maybe you could change the output to "*" syntax like in https://github.com/Freetz-NG/freetz-ng/pull/926#issuecomment-1925284574 , then i could use it without change
You could add the path to "environment.log" in the script (beginning)

**Comment by Ircama** [comment]
The following "read_env" function can read the "env" file via FTP at boot and set the following variables: ProductID, MAPSTART, FULLSIZE, LFS.

It is written to be easily included in push_firmware, works perfectly on the 7590 AX device, is fast, can be run more times and is able to extract valid MAPSTART and FULLSIZE values, as well as CURRENT_LFS and LFS (future LFS for uploading).

```shell
export ip=192.168.178.1

# Download the "env" file and set ProductID, MAPSTART, FULLSIZE, LFS.
# All these references must exist in the "env" file, as well as
# wlan_ssid (as the last value of the file).
# Will not replace variables already valued
# Return 0 if success, else 1
function read_env() {
    echo "Reading 'env' file:"
    TMP_ENV="/tmp/env-$$"
    rm -f "$TMP_ENV"
    echo "open $ip
user adam2 adam2
debug
bin
quote MEDIA SDRAM
get env "$TMP_ENV"
quit" | ftp -v -n -p &
    bg_pid=$!

    count=0  # give 10 seconds to read the file, then kill the FTP
    until (( count == 10 )) || grep -qs wlan_ssid "$TMP_ENV"; do
        sleep 1
        let count=count+1
    done
    kill $bg_pid >/dev/null 2>&1
    wait $bg_pid
    test -f "$TMP_ENV" || return 1
    env_file=$(<"$TMP_ENV")
    rm -f "$TMP_ENV"

    # All references must exist to continue
    [[ "$env_file" == *"memsize "* ]] || return 1
    [[ "$env_file" == *"linux_fs_start "* ]] || return 1
    [[ "$env_file" == *"ProductID "* ]] || return 1
    [[ "$env_file" == *"firstfreeaddress "* ]] || return 1

    enval=$(echo "$env_file" | sed '/^memsize[\t ]/!d; s/^memsize[\t ]*//; s/\r//')
    [ -z "$enval" ] && echo "Invalid value for memsize." && return 1
    [ -z "$FULLSIZE" ] && [ "$enval" != "${enval#0x}" ] && FULLSIZE="$enval"

    enval=$(echo "$env_file" | sed '/^linux_fs_start[\t ]/!d; s/^linux_fs_start[\t ]*//; s/\r//')
    [ "$enval" != "0" -a "$enval" != "1" ] && echo "Invalid value for linux_fs_start." && return 1
    CURRENT_LFS="$enval"
    [ -z "$LFS" ] && LFS="$(( ($enval + 1) % 2))" #other
    [ "$LFS" == "9" ] && LFS="$enval" #current

    enval=$(echo "$env_file" | sed '/^ProductID[\t ]/!d; s/^ProductID[\t ]*//; s/\r//')
    [ -z "$enval" ] && echo "Invalid value for ProductID." && return 1
    [ -z "$ProductID" ] && ProductID="$enval"

    enval=$(echo "$env_file" | sed '/^firstfreeaddress[\t ]/!d; s/^firstfreeaddress[\t ]*//; s/\r//')
    [ -z "$enval" ] && echo "Invalid value for firstfreeaddress." && return 1
    [ -z "$MAPSTART" ] && [ "$enval" != "${enval#0x}" ] && MAPSTART="$enval"
    echo -e "'env' file downloaded with valid values.\n"
    return 0
}

read_env

echo "ProductID=$ProductID"
echo "MAPSTART=$MAPSTART"
echo "FULLSIZE=$FULLSIZE"
echo "LFS=$LFS"
```

Example of run:

```
$ while ! ping -c1 -w1 192.168.178.1 > /dev/null; do echo -n ".";done; ./read_env
..............Connected to 192.168.178.1.
220 ADAM2 FTP Server ready
331 Password required for adam2
230 User adam2 successfully logged in
Remote system type is AVM.
Debugging on (debug=1).
---> TYPE I
200 Type set to BINARY
---> MEDIA SDRAM
200 Media set to MEDIA_SDRAM
local: /tmp/env-2558 remote: env
---> PASV
227 Entering Passive Mode (192,168,178,1,12,14)
---> RETR env
150 Opening BINARY data connection
ProductID=Fritz_Box_HW259
MAPSTART=0x80000000
FULLSIZE=0x0c000000
LFS=0
```

I will use the above function to create a new PR replacing this one in order to support the 7590 AX device.

**Pull request merged**
