### PR TITLE
Mosquitto enhancement, reload, mosquitto_passwd, externalize

### PR DESCRIPTION
**Pull request by pfichtner**
- Support for reloading (instead of restarting), see [comment](https://github.com/Freetz-NG/freetz-ng/pull/466#issuecomment-1046072399)
- Building mosquitto_passwd, see [discussion](https://github.com/Freetz-NG/freetz-ng/discussions/463)
- Support for externalizing broker (mosquitto), mosquitto_passwd, and clients (mosquitto_pub, mosquitto_sub)

### CODE REVIEW

**Comment by fda77** [comment]
Thx. Should i "squash" everything into 1 commit by Github Webinterface? Or just merge all commits? I'm not sure what Git(hub) does with all the not realated commits

**Comment by pfichtner** [comment]
Feel free to squash

**Comment by pfichtner** [comment]
(but merge should also work without any problems)

**Comment by pfichtner** [comment]
If you suspect any problem please close the PR unmerged and I'll provide a new "clean" one

**Comment by fda77** [comment]
I squashed, the single commits have not all "mosquitto" in comment, eg "supporting reload"

**Comment by fda77** [comment]
Btw, you could change/delete commits of a PR by "git push --force", no need to delete

**Pull request merged**
