### PR TITLE
bump xsltproc to version 1.1.37

### PR DESCRIPTION
**Pull request by harryboo**

### CODE REVIEW

**Comment by fda77** [comment]
You have noticed the invitation? Seems ive forgotten the obfuscation patch

**Comment by harryboo** [comment]
i have removed the obfuscation patch (work in progress).

**Comment by fda77** [comment]
When "squash" to merge is used, the openvpn changes are not visible

**Comment by harryboo** [comment]
Can you tell me how to correct this?

**Comment by harryboo** [comment]
So i think now everything is iO...

**Comment by fda77** [comment]
It was not needed to remove the openvpn change+revert, because 
> When "squash" to merge is used, the openvpn changes are not visible

Sqush is what you see on the " Files changed" tab above

> You have noticed the invitation?

**Comment by harryboo** [comment]
Accepted....

**Comment by fda77** [comment]
Bad timing, again :D

**Pull request merged**
