### PR TITLE
add 3490-hardware 7490-software alien

### PR DESCRIPTION
**Pull request by LizenzFass78851**
Based on the inspiration from https://github.com/Freetz-NG/freetz-ng/discussions/1030, I have to make the alien firmware (without [TK firmware](https://github.com/Freetz-NG/freetz-ng/blob/dca42a1875f5399af8bcd989c8efca501a151aa7/patches/cond/100-aliens/scripts/100-7520v1_7530.sh#L3-L6)) buildable based on the [7520 alien template](https://github.com/Freetz-NG/freetz-ng/commit/65bc7ef13210838436b25fcd6f110a38cbee8371).

Unfortunately, I don't have a 7490 or a 3490, I just want to help with creating the alien firmware with this pr.

So it needs testing.

### CODE REVIEW

**Comment by fda77** [comment]
Thank you but i think this is not a good idea without hardware to test.
So it is unsure if
 - wlan works (eg same hardware)
 - usb works (eg same hardware)
 - dsl works (eg same hardware)

Maybe you need a replace-kernel with alien specific patches, you could only know with hardware

https://www.router-faq.de/?id=fbinfo&hwf=fb3490 shows that the 3490 has no dect, so the alien should disable and remove everything related, including smarthome...

And the string "mips34_512MB_xilinx_vdsl_dect446_4geth_2ab_isdn_nt_te_pots_2usb_host_wlan11n_27490" you try to replace does not exists in the file "install" but "rc.conf" (an older alien should be a better template) - you dont know if the build firmware is accepted at all

The 7520 alien works, i know it because im using it

--

You could say, just lets add it and wait until some test it, search https://freetz-ng.github.io/freetz-ng/FIRMWARES.html for "UNTESTED" and you will see reporting is not really working

**Comment by LizenzFass78851** [comment]
> And the string "mips34_512MB_xilinx_vdsl_dect446_4geth_2ab_isdn_nt_te_pots_2usb_host_wlan11n_27490" you try to replace does not exists in the file "install" but "rc.conf" (an older alien should be a better template) - you dont know if the build firmware is accepted at all

Up to OS 7.12, the string with the install type can still be seen under `/var/install`. In newer versions, this is no longer present under `/var/install`.

extract from `/var/install` from `FRITZ.Box_7490-07.12.image`
```bash
.....
# Fritz_Box_HW185
if [ -z "$DISABLE_Fritz_Box_HW185" ] ; then
   echo testing acceptance for device Fritz_Box_HW185 ...
   if /etc/version --install=mips34_512MB_xilinx_vdsl_dect446_4geth_2ab_isdn_nt_te_pots_2usb_host_wlan11n_27490 ; then
       echo device has installtype mips34_512MB_xilinx_vdsl_dect446_4geth_2ab_isdn_nt_te_pots_2usb_host_wlan11n_27490
.....
```

-----

> You could say, just lets add it and wait until some test it, search https://freetz-ng.github.io/freetz-ng/FIRMWARES.html for "UNTESTED" and you will see reporting is not really working

would be a good idea. Otherwise there would be no way for me to test it myself. With a bit of luck it will be similar to the 7520 alien, although that is not yet known until there are testers who report on it.
Otherwise, it can be reverted if test reports on the serial console indicate various difficult (kernel related) errors.

**Comment by fda77** [comment]
Ive tested only newest firmware, andere there this string is missing, so installing alien wont work.
Loading dect driver of 7490 image will also fail with 3490
imho there is no alilen because of differen hardware / incompatible drivers
And i remember (from a openwrt issue) 7490 has 2 cpus, the 2nd "wasp" is for wlan only. Has 3490 mltiple cpus?
From 5490 alien-try i remember the pins of the network stack dont match, and a kernel change was needed
So i think this will not work without testing .. but you could ask for tester: https://www.ip-phone-forum.de/threads/315562/

**Comment by LizenzFass78851** [comment]
> 7490 has 2 cpus, the 2nd "wasp" is for wlan only.

According to boxmatrix.info, both the 3490 and the 7490 have the same WLAN specs and the same CPUs.

Screenshot_20241004_185323_Chrome
Screenshot_20241004_185309_Chrome

**Comment by fda77** [comment]
You could use "irc" to contact "hippi" (owner of boxmatrix and sometimes foggy) and ask about this alien.
He has also alot of old devices to test

**Comment by fda77** [comment]
On the screenshot you could see 3490 has no internal POTS and ISDN - which should also be removed from 7490 image

Before that you have to make "remove telephony patch"  compatible with FOS 7, it works only up to 6.2
https://github.com/Freetz-NG/freetz-ng/blob/master/config/ui/patches.in#L1040

**Comment by LizenzFass78851** [comment]
I read some information from [boxmatrix.info](https://boxmatrix.info/wiki/FREETZ_TYPE_549X_7490) and applied some of the changes from the link mentioned ([with tk firmware](https://github.com/Freetz-NG/freetz-ng/blob/39e35438b924653c03cbfdee7eee7909340e55e4/patches/cond/100-aliens/scripts/100-3490_7490.sh#L3-L6)).
(I can't test it at the moment)

> Loading dect driver of 7490 image will also fail with 3490

With this [change the loading of the dect driver is prevented](https://github.com/Freetz-NG/freetz-ng/blob/39e35438b924653c03cbfdee7eee7909340e55e4/patches/cond/100-aliens/scripts/100-3490_7490.sh#L41) and [removed](https://github.com/Freetz-NG/freetz-ng/blob/39e35438b924653c03cbfdee7eee7909340e55e4/patches/cond/100-aliens/scripts/100-3490_7490.sh#L55)

> From 5490 alien-try i remember the pins of the network stack dont match, and a kernel change was needed

The link mentioned also mentioned something about LAN ports. This is [patched](https://github.com/Freetz-NG/freetz-ng/blob/39e35438b924653c03cbfdee7eee7909340e55e4/patches/cond/100-aliens/scripts/100-3490_7490.sh#L44) using the alien script.

> On the screenshot you could see 3490 has no internal POTS and ISDN - which should also be removed from 7490 image

The workaround with dect does patch the S11 piglet. I cannot say whether this also prevents the loading of isdn and pots .bit at the same time. These files are also [removed by the alien script](https://github.com/Freetz-NG/freetz-ng/blob/39e35438b924653c03cbfdee7eee7909340e55e4/patches/cond/100-aliens/scripts/100-3490_7490.sh#L53-L54), as can be seen from the link from boxmatrix.info.

-----

Regarding the LEDs, the kernel is copied so that the LEDs light up in the correct definition. (Because there are differences in the LEDs on the 7490 and 3490. For example, the 7490 has the DECT LED and the 3490 has an LED for LAN instead.)

**Comment by LizenzFass78851** [comment]
I think the interest in the alien firmware for the 3490 is probably not that great and the fact that I have no way of testing it because I don't have the device in question, I admit defeat and estimate that since these are older devices, it probably wouldn't make much sense and according to reports, [support for the 7490 has also been declared over](https://www.deskmodder.de/blog/2024/10/07/fritzbox-7490-nach-12-jahren-gibt-es-keine-feature-updates-mehr/). You can't get any further than 7.5x. I know I didn't ask boxmatrix.info or ask in forums about testers but I think the words from the [first comment](https://github.com/Freetz-NG/freetz-ng/pull/1050#issuecomment-2393675300) in this PR convinced me in retrospect that it is a bad idea to want to provide something as a pull request without having the opportunity to test it yourself.

**Comment by fda77** [comment]
Without any tests this does not help. please ask
 - in the linked ippf thread for a tester
 - in irc hippi to test
 - or here in the other diskussion anout this alien for a tester

if this is added untested, the user a requiring ME to by MYSELF such a device to make it work 100% - what i will not do

**Pull request closed without merging**
