### PR TITLE
add new python module mysql-connector 8.0.21

### PR DESCRIPTION
**Pull request by lherschi**

### CODE REVIEW

**Comment by fda77** [comment]
The `PYTHONHOME` usage is not optimal.
Freetz has pyton 2 + 3 as host tools to be able to eg run scripts and because host system has only 1 of both python versions
With `PYTHONHOME=$(HOST_TOOLS_DIR)/usr` you used that python2.

But the `$(call Build/PyMod/PKG ...`  which is defined in https://github.com/Freetz-NG/freetz-ng/blob/master/make/pkgs/python/python-module-macros.mk.in#L49 uses another python in `HOST_PYTHON_BIN:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/bin/hostpython`

This could cause problems. But for me it worked as it is :)

When there is some solution, the `PYTHONHOME` could also be set here for all: https://github.com/Freetz-NG/freetz-ng/blob/master/make/pkgs/python/python-module-macros.mk.in#L20


ADD: If you dont know a better way, is should be sure that python2-host is build before this package with a `_DEPENDS_ON`

**Comment by lherschi** [comment]
PYTHONHOME=$(HOST_TOOLS_DIR)/usr could be chnaged to 
PYTHONPATH=$(HOST_TOOLS_DIR)/usr/lib/$(PYTHON)/lib-dynload.
Then you definitely use the same Python version as hostpython and the default library paths are not changed.

**Comment by fda77** [comment]
Yes, i found https://github.com/Freetz-NG/freetz-ng/blob/master/make/pkgs/python/python.mk#L125 where the python2-host is copied "hostpython". But then i dont understand why the host binary is in the staging directory. The "Build/PyMod/PKG" in https://github.com/Freetz-NG/freetz-ng/blob/master/make/pkgs/python/python-module-macros.mk.in#L49 could then run the binary in tools/ dir ... but anyway it does not matter for this as long as it works :)

PYTHONPATH is set here: https://github.com/Freetz-NG/freetz-ng/blob/master/make/pkgs/python/python-module-macros.mk.in#L22 , is not correct as you set PYTHONHOME for this package? Or what about PYTHONHOME set in python-module-macros.mk.in, then it is set for all

**Comment by lherschi** [comment]
I first created the package without PYTHONHOME. Then I had the following error when building.
ImportError: ~/src/freetz-ng/toolchain/build/mips_gcc-13.2.0_uClibc-1.0.44-nptl_kernel-4.9/mips-linux-uclibc/usr/lib/python2.7/lib-dynload/datetime.so: wrong ELF class: ELFCLASS32
The library used here is the MIPS32 version.  I was then just looking for a way to make the x86-64 version available.
I can't really estimate the changes in the mk files. I don't know the build system well enough for that. If I only set this in the package, I at least don't have to worry about any side effects. I think if another Python module needs PYTONHOME, you can think again about setting it somewhere centrally.

**Comment by fda77** [comment]
If you had chosen a Docsis device, you had not this problem, because they have a x86 (and if your computer is a x86)...
So i dont understand why a host binary should be copied to staging dir which copntains the target architecture files.
But anday, not changing a running system prevents problems :)

**Pull request merged**
