### PR TITLE
mod: update about

### PR DESCRIPTION
**Pull request by friederbluemle**
Thanks for adding me to the list @fda77 :+1:
Just a small update here to make it all lower case 😉

### CODE REVIEW

**Comment by fda77** [comment]
The content of the file is semi-automatic created by this command: https://github.com/Freetz-NG/freetz-ng/blob/master/make/mod/files/root/usr/mww/cgi-bin/freetz.cgi#L9 These are not the Github name! You could delete your email from your GitHub account and add it to another account. Github links all your commits then to the new account. But the "raw" name in the commit keeps unchanged: https://github.com/Freetz-NG/freetz-ng/commit/94358e28dfd84c2407da235c18f8bba5ce08c8d4.patch
git2svn uses also this name: https://trac.boxmatrix.info/freetz-ng/changeset/18542/freetz-ng
So by merging this, the upper/lower case has to be changed every time

**Comment by friederbluemle** [comment]
> The content of the file is semi-automatic created by this command: [https://github.com/Freetz-NG/freetz-ng/blob/master/make/mod/files/root/usr/mww/cgi-bin/freetz.cgi#L9](https://github.com/Freetz-NG/freetz-ng/blob/master/make/mod/files/root/usr/mww/cgi-bin/freetz.cgi?rgh-link-date=2021-09-21T19%3A21%3A45Z#L9) These are not the Github name! You could delete your email from your GitHub account and add it to another account. Github links all your commits then to the new account. But the "raw" name in the commit keeps unchanged: [`94358e2`.patch](https://github.com/Freetz-NG/freetz-ng/commit/94358e28dfd84c2407da235c18f8bba5ce08c8d4.patch)
> git2svn uses also this name: [trac.boxmatrix.info/freetz-ng/changeset/18542/freetz-ng](https://trac.boxmatrix.info/freetz-ng/changeset/18542/freetz-ng)
> So by merging this, the upper/lower case has to be changed every time

Ooh okay, got it! I wrongly assumed these are GitHub usernames (as there are a bunch of other lower case names in the list). Sorry for the confusion!

I'm new to this project, quick question: Is this repo here on GitHub or the svn repo over at https://trac.boxmatrix.info/freetz-ng the "authoritative" (primary) source? I assume they are mirrored? Is there a preferred way of contributing? Maybe there is a document explaining it? ;)

**Comment by fda77** [comment]
https://github.com/Freetz-NG/freetz-ng#readme could help. (This) GitHub is mentioned at "clone" and BitBucket, GitLab & BoxMatrix in "mirrors"
The Trac on BoxMatrix is a backup of www.freetz.org before it was deleted and the main SVN was moved to Git(Hub). Its very helpfull to read old Tickets+Attachements, but much to slow for current Issues

Links to GitHub accounts on "about" page would be nice, but i dont know how to get them just by the commits (or if it is even possible). Using svn for the usernames is much simpler, as there is no autor, commiter etc ;-)

**Comment by friederbluemle** [comment]
Makes sense, thanks for the info! :+1:

**Comment by fda77** [comment]
I just noticed, here are also "mirrors" listed: https://freetz-ng.github.io/#timeline

**Pull request closed without merging**
