### PR TITLE
5490 as alien 7490

### PR DESCRIPTION
**Pull request by jschwartzenberg**
This is untested by me as of now. I hope to do it soon.

### CODE REVIEW

**Comment by fda77** [comment]
- Code in 100-549X_7490.sh  is duplicated
- By removing FREETZ_TYPEs in download.in, english buulds will not work

**Comment by fda77** [comment]
6 weeks gone

**Comment by jschwartzenberg** [comment]
Yep, I haven't been able to test anymore. I hope someone might be able to rebase if they still need it Hopefully the effort over at https://github.com/kestrel1974/openwrt/ can replace the use cases for which this patch was originally created.

**Comment by fda77** [comment]
I think nobody needs it.
After 5490 got no 7.20+ it seem the device is abandoned. That was the reason for hippi to experiment with alien. But now it has 7.25+ by avm

In the alien script are the first 123 lines still the same (or most the same, ive not checked it) than the last 123

**Pull request closed without merging**
