### PR TITLE
Speedport w504v support

### PR DESCRIPTION
**Pull request by BojanSof**
Add support for [Speedport W504V](https://boxmatrix.info/wiki/Speedport_W_504V_MK) box (AVM variant).

Big thanks to hippie2000 from [boxmatrix.info](https://boxmatrix.info/) who has very big knowledge about AVM hardware and firmware, and provided invaluable instructions for adding Freetz support for this box.
It ended up in a [tutorial ](https://boxmatrix.info/wiki/FREETZ_TYPE_W504V_7270_V3) that can be used as a starting point for what it takes to make aliens work with Freetz.
A lot of credits for this PR should go to him.

### CODE REVIEW

**Comment by fda77** [comment]
Thank you! Does it work on your device?
Yes, i know hippi has good knowledge of old hw and aliens ;)
Can you attach the fw_Speedport_W504V_avm_dump_v92.05.04.image here? I cant test without (separate post please, so it could be deleted later)
GerTelekom called its non-avm hardware "Typ A" earlier, see download dir `downloads/Speedport/Speedport W 504V Typ A/` from [theme-224064007/Speedport-W-504V](https://web.archive.org/web/20150404165726/http://hilfe.telekom.de:80/hsp/cms/content/HSP/de/3388/FAQ/theme-224064007/Speedport-W-504V). So IMHO the "MK" should be "Typ B" like other speedport devices.
Has you device the same hw features and case like the "A" [https://www.router-faq.de/?id=spinfo&hws=speedportw504v](https://www.router-faq.de/?id=spinfo&hws=speedportw504v) ?

**Comment by BojanSof** [comment]
@fda77 Yes, it works on my device, I've tested with both fritz OS 5.24 and 5.53.

I can send you the dump, but if you can give me mail so I can send it privately, as I don't want to put it in public, as it is proprietary. Thanks for understanding.

I think the hardware features from high level look the same as typ A.

**Comment by fda77** [comment]
@BojanSof: whats your irc name?

**Comment by BojanSof** [comment]
> @BojanSof: whats your irc name?

@fda77 My IRC nick is MasterOfReality. I'll probably be available on IRC in the evening hours.

**Pull request merged**
