### PR TITLE
getdns - change path for pid file and config

### PR DESCRIPTION
**Pull request by harryboo**

### CODE REVIEW

**Comment by fda77** [comment]
Sry, 10 minutes to late :) e3ced57a7e6d5aec445f0e5068dac54ebe632c0c
The "unbound" i set is useless in the way stubby is compiled but does not harm

**Comment by harryboo** [comment]
Ignore this pull request.
Your solution is the best....

**Comment by harryboo** [comment]
And again to late...  ;-)

**Comment by fda77** [comment]
With cmake you can run `cd DIRECTORY && cmake -LA .` (reminder: https://github.com/Freetz-NG/freetz-ng/blob/master/make/pkgs/getdns/getdns.mk#L45)  to see all usable "configure" options.
Maybe you find other usefull things

**Comment by fda77** [comment]
Also stubby could use the libs libuv and libev which are available in freetz. But they are disbled (like with older version) and i do not knwo what is better with them

**Pull request closed without merging**
