### PR TITLE
Add manual option to push_firmware to allow interactive FTP

### PR DESCRIPTION
**Pull request by Ircama**
__Add manual option to *push_firmware* to allow interactive FTP__

Add the `-m` option of *push_firmware* connects to the device via FTP and allows manual commands (for development).

### CODE REVIEW

**Comment by fda77** [comment]
as you know from you 1st question, people use every option the can find, if it is silly or not. so im not sure to add an option only you will use...
beside that it is a bad idea to search "ftp" before set the PATH - because this forces 99% the system ftp to be used, which you complained about (error warning)

**Comment by Ircama** [comment]
> as you know from you 1st question, people use every option the can find, if it is silly or not. so im not sure to add an option only you will use...

When this happens, it generally means that a user receives an error and perceives that there is some wrong default option adopted for the specific (new/untested) device, but there is not enough documentation to drive to the appropriate strategy to solve the issue. This option has the goal to allow developers to interactively test the device when the adopted FTP commands are not appropriate. Notice that I mentioned "(for development)" in its description label. That was for instance the case of 7590 AX, where e.g. the `quote REBOOT` command halts the device without issuing an actual reboot, and the subsequent `quote BYE` experiment also failed. I also used this strategy to manually test one by one the parameters obtained from the analysis of the recovery tool log before entering these into the code and do final testing. Without the automation in this PR, one has to develop a script that pings the device until it becomes available after a reboot, so that the FTP can be immediately run in the subsequent short timing window, before the device disables its FTP server.

**Comment by Ircama** [comment]
> beside that it is a bad idea to search "ftp" before set the PATH - because this forces 99% the system ftp to be used

The logic [in the related lines](https://github.com/Freetz-NG/freetz-ng/blob/d7de68a822953d759f221b0d8340ac94ca25577a/tools/push_firmware#L43-L46) only apply when issuing an interactive FTP, where a developer is expected to be using a Linux system already installing the FTP client. So, not with the default process.

When using the `-m` option, the logic checks whether the Linux system already has the ftp client; if exists, it uses it, otherwise it uses the default CURL ftp client included in the repository (which is the program used by *push_firmware* to interact with the device without the `-m` option).

The advantage of the Linux ftp client is to enable command editing and history, that the curl ftp client does not provide, because it is not oriented to user interaction.

If you anyway do not want this, I'll remove the logic.

> , which you complained about (error warning)

Edit: removed the following sentence because it is not true
~~If you refer to `ftp: setsockopt (ignored): Permission denied`, I'm afraid this warning also occurs with the curl FTP of *freetz-ng* .~~

**Comment by fda77** [comment]
> If you refer to ftp: setsockopt (ignored): Permission denied, I'm afraid this warning also occurs with the curl FTP of freetz-ng .

Because of your change!!!!!

**Comment by Ircama** [comment]
> > If you refer to ftp: setsockopt (ignored): Permission denied, I'm afraid this warning also occurs with the curl FTP of freetz-ng .
> 
> Because of your change!!!!!

You are totally right, I apologize. I updated the PR removing the usage of the stock ftp for interactive mode. We just need to be aware that the command editing and history are not available.

**Comment by fda77** [comment]
Yes, thats because i disabled readline support to reduce libs... But you could change https://github.com/Freetz-NG/freetz-ng/tree/master/make/host-tools/netkit-ftp-host by remove the disable-readline-patch and instead build it static. Use "make netkit-ftp-host-recompile" and "ldd" to test
Btw, what "development commands" you intend to use with this option?

**Comment by Ircama** [comment]
> Btw, what "development commands" you intend to use with this option?

I just tested some ways to (unsuccessfully) try rebooting the 7590 AX device: `quote BYE`, `quote REBOOT`. Then I tested the commands one by one when I calculated the values from the recovery tool. Indeed I have to say that this option is not strictly mandatory: there is an easy alternative way via command line:

```
while ! ping -c1 -w1 192.168.178.1 > /dev/null; do echo -n ".";done; tools/ftp -n -p -v 192.168.178.1
```

**Comment by fda77** [comment]
If i REMEMBER correctly, avm does not use reboot for your device with recovery! after loading the new image to ram, this is started without reboot and the image reboote with linux tools after it flashed itself.
But with my 7490 which is also same ramboot/nand/inmemory reboot works (and PF as it was before "bye")

> Btw, what "development commands" you intend to use with this option?

?

**Comment by Ircama** [comment]
> If i REMEMBER correctly, avm does not use reboot for your device with recovery! after loading the new image to ram, this is started without reboot and the image reboote with linux tools after it flashed itself.

Yes, I think so too. It looks like that once the FTP upload succeeds on 7590 AX, it is loaded immediately.

> Btw, what "development commands" you intend to use with this option?

This option is not strictly necessary. Before discovering the right parameters to upload the firmware to the 7590 AX model, I did a number of manual tests and I found the interactive mode useful; I typed commands like the following ones, with different parameter values.

```
quote MEDIA SDRAM
quote SETENV memsize 0x08d1d900
quote SETENV kernel_args_tmp mtdram1=0x88d1d900,0x8c000000
quote PASV
put /tmp/freetz_V7V/ramboot.flash 0x88d1d900 0x8c000000
```

I considered useful to document this with a PR, for others who might run into a similar problem.

**Comment by fda77** [comment]
I dont think anyone calculates these commands manually. What about `return $?` ? (i dont have read the script!)

**Pull request merged**
