### PR TITLE
unrar: add version 6.2.5

### PR DESCRIPTION
**Pull request by harryboo**
Hope this is a better solution...

### CODE REVIEW

**Comment by fda77** [comment]
The patches fit for both versions? if not move them and add:
``` $(PKG)_CONDITIONAL_PATCHES+=$(if $(FREETZ_PACKAGE_x_VERSION_ABANDON),abandon,current)```

Does it not depende on gcc version instead FREETZ_KERNEL_VERSION_2_6_13? Available symbols:
config FREETZ_TARGET_GCC_4_MIN
config FREETZ_TARGET_GCC_4_6_MIN
config FREETZ_TARGET_GCC_4_7_MIN
config FREETZ_TARGET_GCC_4_8_MIN
config FREETZ_TARGET_GCC_4_9_MIN
config FREETZ_TARGET_GCC_5_MIN
config FREETZ_TARGET_GCC_8_MIN
config FREETZ_TARGET_GCC_9_MIN
config FREETZ_TARGET_GCC_4_MAX
config FREETZ_TARGET_GCC_5_MAX
config FREETZ_TARGET_GCC_8_MAX
config FREETZ_TARGET_GCC_9_MAX

You know you can hit the merge button by yourself? And that you can update this pr or replace its content completely?

**Comment by harryboo** [comment]
Hi, yes i know that i can merge a pr by myself, but as you can see it is better that some more eyes will have a look at it.

I will change the dependency, good remark...

What do you think: Do we need to split the patches dir for booth versions?
At the moment the patches will work with both.

**Comment by fda77** [comment]
I have always for each version a separate directory, with next versions after running autofix all the time sometime the old version does not longer match. And i never check the old version

**Comment by harryboo** [comment]
ok, i will create separate dirs for the versions

**Pull request merged**
