### PR TITLE
pseudo cannot handle find well.  ls -1R can be used to emulate find

### PR DESCRIPTION
**Pull request by Bonpournickel**
find tool is replaced with ls -R as input for cases. I don't have an opportunity to test it on avm devices. I don't have any here.
It compiles well with any pseudo complain. I didn't test fakeroot. My default shell is mksh but it has been tested with bash on the latest linux kernel 5.16.1 and unstable tools availables from gentoo repositories.

make menuconfig is set to APTGURU

I hope it works...

B

### CODE REVIEW

**Comment by Bonpournickel** [comment]
Also no conflicts

**Comment by fda77** [comment]
Hello, which problem you want fix with this? Does you "find" command not works as expected? Changing so much working code is risky.
I'm building images by myself with pseudo and have no problems noticed
What about to use a compatible find command? It should be enought to place/link it in `tools/path/` so the scripts use it as first

**Comment by Bonpournickel** [comment]
yes find creates the problem and pseudo cannot handle pipe well (fails with xargs for instance).

I'm using pseudo from debian https://git.dgit.debian.org/pseudo commit 7778a4488c96627924ad0191e19aa15cf3ad5903
and kernel 5.16.1. find comes from findutils-4.8.0.

I'm glad it works for you . In my case pseudo fails on every find call. I don't have a link to find in path directory.
I'll try it. 

Thx for the suggestion.

**Comment by fda77** [comment]
It does not matter if/what version of pseudo you have installed, as freetz uses its own biarch version. You are sure you selected pseudo in menuconfig at all? Or kept you the default which is not pseudo?!
On fedora ive the same find version. So it seems to be *again* some debian problem cause by some strange things in this distribution. There where some other issues with it which needed workarounds.
I think its the best to find the cause of the non-default behavious with debian

**Comment by Bonpournickel** [comment]
Sorry it doesn't work. I still get

>[..]
>got *at() syscall for unknown directory, fd 5
>unknown base path for fd 5, path data
>couldn't allocate absolute path for 'data'.
>got *at() syscall for unknown directory, fd 5
>unknown base path for fd 5, path data
>couldn't allocate absolute path for 'data'.
>find: 'build/modified/filesystem/data': Bad address
>got *at() syscall for unknown directory, fd 5
>unknown base path for fd 5, path data
>couldn't allocate absolute path for 'data'.
>[..]

and without the following changes the script loops

>./fwmod: fork: retry: Resource temporarily unavailable
>./fwmod: fork: retry: Resource temporarily unavailable
>./fwmod: fork: retry: Resource temporarily unavailable
>^Cmake: *** [Makefile:306: firmware-nocompile] Interrupt
```
--- a/fwmod
+++ b/fwmod
@@ -342,7 +342,7 @@ FAKEROOT_CACHE_DIR="$ABS_BASE_DIR/.fakeroot-cache"
 [ "$FREETZ_ROOTEMU_FAKEROOT" != 'y' ] && FAKEROOT_CACHE_DB="$FAKEROOT_CACHE_DIR/files.db" || FAKEROOT_CACHE_DB="$FAKEROOT_CACHE_DIR/fakeroot.cvs"
 
 # Are we in a fakeroot context?
-if [ -n "$FWMOD_RECURSIVE" ] && [ $UID -eq 0 ]; then
+if [ -n "$FWMOD_RECURSIVE" ] || [ $UID -eq 0 ]; then
        # Yes -> fakeroot is active
        # Make sure fakeroot call came from ourselves so we can assume the cache settings to be correct
        if [ $((FWMOD_RECURSIVE)) -eq 0 ] || [ "$SELF" != "$(sed -nr 's/^Name:[[:blank:]]+(.*)/\1/p' /proc/$FWMOD_RECURSIVE/status)" ]; then
```
I made a script that use pseudo and find. I cannot reproduce it. The problem should be elsewhere...

the script looks like that and ... works:
```
#!/bin/bash -x
for ((i=0; i<=$#; i++)); do
    CMDLINE_ORIG[i]="${!i}"
done
BASE_DIR="$(dirname "$0")"
ABS_BASE_DIR="$(readlink -f "$BASE_DIR")"
TOOLS_DIR="${ABS_BASE_DIR}/tools"
FAKEROOT_CACHE_DIR="$ABS_BASE_DIR/.fakeroot-cache"
HOME=$BASE_DIR
export PSEUDO_PREFIX=$TOOLS_DIR/build
export PATH=$TOOLS_DIR/path:/usr/bin:/bin:/usr/sbin:/sbin
if [ -n "$FWMOD_RECURSIVE" ] || [ $UID -eq 0 ]; then
find . | xargs echo | wc -l
else
PSEUDO_PREFIX="$TOOLS_DIR/build" PSEUDO_LOCALSTATEDIR="$FAKEROOT_CACHE_DIR"                  "$TOOLS_DIR/build/bin/pseudo"  -B  #scan
FWMOD_RECURSIVE="$$" PSEUDO_PREFIX="$TOOLS_DIR/build" PSEUDO_LOCALSTATEDIR="$FAKEROOT_CACHE_DIR" PSEUDO_DEBUG="1" "$TOOLS_DIR/build/bin/pseudo" '--' "${CMDLINE_ORIG[@]}"
PSEUDO_PREFIX="$TOOLS_DIR/build" PSEUDO_LOCALSTATEDIR="$FAKEROOT_CACHE_DIR"                  "$TOOLS_DIR/build/bin/pseudo"  -S  #halt
exit
fi
```

Any ideas

**Comment by Bonpournickel** [comment]
> It does not matter if/what version of pseudo you have installed, as freetz uses its own biarch version. You are sure you selected pseudo in menuconfig at all? Or kept you the default which is not pseudo?! On fedora ive the same find version. So it seems to be _again_ some debian problem cause by some strange things in this distribution. There where some other issues with it which needed workarounds. I think its the best to find the cause of the non-default behavious with debian

The system is Gentoo. I just create an ebuild for pseudo because it is not available in the distro and because I get at first the following message  I thought was related to pseudo. The real reason was the missing /usr/sbin:/sbin  in user PATH.

```
tools/prerequisites: ligne 17: ldconfig : commande introuvable
ERROR: The library 'libsqlite3.so' was not found in /etc/ld.so.cache
Makefile:136: *** Some build prerequisites are missing! See '.prerequisites' for why. Please install the missing packages before trying again. See https://freetz-ng.github.io/freetz-ng/PREREQUISITES for installation hints. Arrêt.
```

To answer your question, that is what is in .config related to pseudo/fakeroot

```
#                                                                               
# Tools and toolchains options ------------------------                         
#                                                                               
FREETZ_TOOLCHAIN_MINIMIZE_REQUIRED_GLIBC_VERSION=y                              
# FREETZ_TOOLCHAIN_32BIT is not set                                             
FREETZ_TOOLCHAIN_CCACHE=y                                                       
# FREETZ_ROOTEMU_FAKEROOT is not set                                            
FREETZ_ROOTEMU_PSEUDO=y                                                         
# FREETZ_HOSTTOOLS_DOWNLOAD is not set                                          
# end of Toolchain options     
```

**Comment by fda77** [comment]
"ldconfig" is used by "tools/prerequisites" to check if you have installed prerequisites. As it does not exist, it could not check it. It seems there should be an additional check if the tool is available at all...
Freetz uses the pseudo from "tools/make/pseudo-host/" (or the precompiled - if you selected it in menuconfig)

**Comment by fda77** [comment]
If you search for missing ldconfig with debian/gentoo, you will notice its because broken `$PATH` variable in debian.
To fix this bug run `export PATH=$PATH:/sbin` , see https://debianforum.de/forum/viewtopic.php?t=170288 (german)

**Comment by Bonpournickel** [comment]
I'm still struggling with pseudo and freetz ea66ca8797eb309d1d4128c6bb27e5accc0adde0.
I desinstalled pseudo and I'm using freetz own version for now to avoid confusion. Both versions differ only with  fcntl64(), procfs symlink expansion and #define O_PATH  010000000 if glibc is greater than 2.16 (it is!)

Makefile differences were,
```
--- /var/local/freetz-ng/source/host-tools/pseudo-0cda3ba5f94aed8d50652a99ee9c502975aa2926/biarch/Makefile	2022-02-11 17:17:54.778177619 +0100
+++ ./Makefile	2022-02-11 17:11:01.648463344 +0100
@@ -7,15 +7,15 @@
 #
 
 # configuration flags
-PREFIX=/var/local/freetz-ng/tools/build
-LIBDIR=/var/local/freetz-ng/tools/build/lib64
+PREFIX=/usr
+LIBDIR=/usr/lib64
 SUFFIX=
 SQLITE=/usr
 SQLITE_LIB=lib64
 SQLITE_MEMORY=-DUSE_MEMORY_DB
-FORCE_ASYNC=
+FORCE_ASYNC=-DPSEUDO_FORCE_ASYNC
 EPOLL=
-XATTR=false
+XATTR=true
 XATTRDB=false
 PROFILING=
 ifeq (true,$(PROFILING))
@@ -31,9 +31,9 @@
         $(call cond,PROFILING,PSEUDO_PROFILING)
 PASSWD_FALLBACK=""
 BITS=64
-ARCH_FLAGS=-Wno-cast-function-type -Wno-nonnull-compare -fcommon
-MARK64=64
-RPATH=
+ARCH_FLAGS=
+MARK64=
+RPATH= -Wl,-R$(SQLITE)/$(SQLITE_LIB)
 VERSION=1.9.0
 
 LIB=lib64
```

Also,  freetz pseudo 0cda3ba5f94aed8d50652a99ee9c502975aa2926 last commit only and executing
`make olddefconfig && make`, the process ends with,

```
[..]
done.
mkdir -p packages/target-mips_gcc-5.5.0_uClibc-1.0.14-nptl_kernel-3.10/syslogd-cgi-0.2.3/root
if test -d make/syslogd-cgi/files; then 	tools/tar-gnu -cf - -C make/syslogd-cgi/files --exclude=.svn --exclude=.git --exclude=.gitignore --exclude=.build-prereq-checked --exclude=.unpacked --exclude=.configured --exclude=.compiled --exclude=.installed . | tools/tar-gnu -xf - -C packages/target-mips_gcc-5.5.0_uClibc-1.0.14-nptl_kernel-3.10/syslogd-cgi-0.2.3; fi
which: no pv in (/var/local/freetz-ng/tools/path:/bin:/usr/bin:/home/emu/bin:/usr/games/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin)
which: no pv in (/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/bin:/usr/bin:/home/emu/bin:/usr/games/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin)
which: no pv in (/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/bin:/usr/bin:/home/emu/bin:/usr/games/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin)
which: no pv in (/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/bin:/usr/bin:/home/emu/bin:/usr/games/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin)
which: no pv in (/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/bin:/usr/bin:/home/emu/bin:/usr/games/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin)
which: no pv in (/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/bin:/usr/bin:/home/emu/bin:/usr/games/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin)
which: no pv in (/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/bin:/usr/bin:/home/emu/bin:/usr/games/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin)
[get more and more ...]
which: no pv in (/var/local/freetz-ng/tools/path[..]:/var/local/freetz-ng/tools/path:/bin:/usr/bin:/home/emu/bin:/usr/games/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin)
which: no pv in (/var/local/freetz-ng/tools/path[..]:/var/local/freetz-ng/tools/path:/var/local/freetz-ng/tools/path:/bin:/usr/bin:/home/emu/bin:/usr/games/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin)
./fwmod: fork: retry: Ressource temporairement non disponible
./fwmod: fork: retry: Ressource temporairement non disponible
./fwmod: fork: retry: Ressource temporairement non disponible
./fwmod: fork: retry: Ressource temporairement non disponible
./fwmod: fork: Ressource temporairement non disponible
FINISHED
[ 64 times as many]
FINISHED
```
The uncontrolled recursion ends with ``ressource temporary unavailable``.

**Comment by Bonpournickel** [comment]
I can confirm it. I need at least to correct the recusion problem to change the following line in the script,

```
diff --git a/fwmod b/fwmod
index 8b7ae9090..3a975c955 100755
--- a/fwmod
+++ b/fwmod
@@ -342,7 +342,7 @@ FAKEROOT_CACHE_DIR="$ABS_BASE_DIR/.fakeroot-cache"
 [ "$FREETZ_ROOTEMU_FAKEROOT" != 'y' ] && FAKEROOT_CACHE_DB="$FAKEROOT_CACHE_DIR/files.db" || FAKEROOT_CACHE_DB="$FAKEROOT_CACHE_DIR/fakeroot.cvs"
 
 # Are we in a fakeroot context?
-if [ -n "$FWMOD_RECURSIVE" ] && [ $UID -eq 0 ]; then
+if [ -n "$FWMOD_RECURSIVE" ] || [ $UID -eq 0 ]; then
        # Yes -> fakeroot is active
        # Make sure fakeroot call came from ourselves so we can assume the cache settings to be correct
        if [ $((FWMOD_RECURSIVE)) -eq 0 ] || [ "$SELF" != "$(sed -nr 's/^Name:[[:blank:]]+(.*)/\1/p' /proc/$FWMOD_RECURSIVE/status)" ]; then
```

Like you said pseudo from freetz package itself is working. The **os-core** git branch is not. I can now generate an image.
Pseudo team should investigate it.

**Comment by fda77** [comment]
> I desinstalled pseudo and I'm using freetz own version for now to avoid confusion. 

Freetz uses always its own pseudo by `"$TOOLS_DIR/build/bin/pseudo"` in fwmod.
 
A search for `fork: retry: Ressource temporairement non disponible` shows various reasons, like "/tmp is full" or "to low resources" (`ulimit -u`), etc

> Like you said pseudo from freetz package itself is working. The os-core git branch is not. 

Freetz uses the os-core branch... or you want to say the "precompiled" binary is working? This is build by `tools/dl-hosttools` but on a very old ubuntu to be compatible with many linuxes -> in this case the compiling with your system is the problem

>  Are we in a fakeroot context?

I'm not sure if this is a fix, as it works unchanged on other systems (im using fedora 35)...

**Comment by fda77** [comment]
* 19a3a39036697f1ab8b4bb8b2ca1d838b95b7c4e bump pseudo-host

**Pull request closed without merging**
